#!/usr/bin/env python3
"""Produce the proposal's figures, one uv environment at a time.

    reproduce/figures/make_figures.py                 # everything that can be drawn
    reproduce/figures/make_figures.py --list          # the inventory, and what is skipped
    reproduce/figures/make_figures.py 05-band-discovery 05-persistence-ramp
    reproduce/figures/make_figures.py --no-install    # leave prose/fig/ alone

Each generator runs as a subprocess in the smallest environment that can produce
it, exactly as `run_all_tables.sh` runs each table generator under its own
submodule -- a Chapter 5 figure needs scipy, a Chapter 6 figure needs the pinned
`tribble-fis`, and a schematic needs neither.

A generator that fails does not stop the run. Its log goes to stderr, the
summary at the end names it, and the exit status is non-zero -- so "this figure
is broken" is never quietly reported as "this figure is unchanged", which is the
same failure the table harness guards against.

Figures land in `reproduce/outputs/figures/` and are then copied into
`research/proposal-defense/prose/fig/`. Both steps are wanted: the harness
directory is the evidence trail, the prose directory is what the document reads.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

# This driver prints figure titles and skip reasons straight from registry.py,
# which is prose and will acquire a ± or a ² the moment someone writes one.
# Windows defaults stdout to cp1252, so that would kill the driver in its own
# progress print after drawing the figures -- the failure shape `build_pdf.py`,
# the harness emitters and the Chapter 5 driver each hit separately.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

from registry import FIGURES, BY_NAME, harness_name, prose_figures  # noqa: E402

FIG_OUT = os.path.join(ROOT, "reproduce", "outputs", "figures")
PROSE_FIG = os.path.join(ROOT, "research", "proposal-defense", "prose", "fig")


def command(fig):
    """The uv invocation for one generator."""
    cmd = ["uv", "run"]
    if fig.project:
        cmd += ["--project", os.path.join(ROOT, fig.project)]
    for extra in fig.extras:
        cmd += ["--with", extra]
    cmd += ["python", os.path.join(HERE, f"{fig.module}.py")]
    return cmd


def environment(fig):
    """The subprocess environment for one generator.

    A figure that declares an `archive` gets it as `REPRO_ARCHIVE`, which is how
    `harness_data` pins the run it reads. Unpinned, that module resolves to the
    newest archive by `generated:` stamp and then to the loose files in
    `reproduce/outputs/` -- correct for a figure drawn from `run_all_tables.sh`,
    and wrong for one drawn from a study the sweep does not run, because the
    newest sweep archive never carries that study's tables and the loose files are
    gitignored. That combination is why the six study generators raised
    FileNotFoundError from a clean checkout.

    A registry pin BEATS an ambient `REPRO_ARCHIVE`, and that ordering is
    deliberate. It used to be the other way round, so
    `REPRO_ARCHIVE=<sweep-label> make_figures.py` -- the obvious way to redraw a
    document against one run -- silently repointed all six pinned study figures at
    a sweep archive that does not contain their tables. Here that failed loudly,
    five FileNotFoundErrors in a row. It would not have: a study CSV whose name
    collides with a sweep table would have been read instead, and the figure would
    have been drawn from the wrong experiment without a word.

    A pin means the figure comes from a study the sweep does not run, so no sweep
    label can be the right answer for it. Unpinned figures still follow the
    caller's `REPRO_ARCHIVE`, which is the case that override exists for. Use
    `--only <name>` to redraw a pinned figure against something else.
    """
    env = dict(os.environ)
    if fig.archive:
        env["REPRO_ARCHIVE"] = fig.archive
    return env


def show_inventory():
    width = max(len(f.name) for f in FIGURES)
    print(f"{'fig':>5}  {'file':<{width}}  status")
    print(f"{'':->5}  {'':-<{width}}  {'':-<44}")
    for f in FIGURES:
        if f.skip:
            status = "SKIPPED -- see registry.py for why"
        elif f.owner:
            status = f"generated by {f.owner}"
        else:
            env = f.project or "bare env"
            status = f"{f.module}.py  [{env}]"
        # The archive is part of the status, not a footnote: two of these figures
        # would draw silently from a different run if it were unset.
        if f.archive:
            status += f"  <- {f.archive}"
        print(f"{f.number:>5}  {f.name:<{width}}  {status}")
        if f.document:
            print(f"{'':>5}  {'':<{width}}  illustrates {f.document}")

    prose = prose_figures()
    study = [f for f in FIGURES if f.document is not None]
    drawn = sum(1 for f in FIGURES if f.skip is None)
    print(
        f"\n{drawn} of {len(FIGURES)} figures have a generator; "
        f"{len(FIGURES) - drawn} skipped."
    )
    print(
        f"{len(prose)} are the proposal's own (installed into prose/fig/); "
        f"{len(study)} illustrate a study write-up and stay under "
        f"{os.path.relpath(FIG_OUT, ROOT)}."
    )


def install(names):
    """Copy generated PNG/EPS pairs into the prose directory."""
    os.makedirs(PROSE_FIG, exist_ok=True)
    copied = 0
    for name in names:
        for ext in ("png", "eps"):
            src = os.path.join(FIG_OUT, f"{harness_name(name)}.{ext}")
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(PROSE_FIG, f"{name}.{ext}"))
                copied += 1
    return copied


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("only", nargs="*", help="figure names; default is all of them")
    ap.add_argument("--list", action="store_true", help="show the inventory and exit")
    ap.add_argument(
        "--no-install",
        action="store_true",
        help="do not copy the result into prose/fig/",
    )
    args = ap.parse_args()

    if args.list:
        show_inventory()
        return 0

    unknown = [n for n in args.only if n not in BY_NAME]
    if unknown:
        print(
            f"unknown figure(s): {', '.join(unknown)}\n"
            f"run with --list to see the inventory",
            file=sys.stderr,
        )
        return 2

    wanted = [BY_NAME[n] for n in args.only] if args.only else list(FIGURES)

    made, skipped, failed = [], [], []
    for fig in wanted:
        if fig.skip:
            skipped.append(fig)
            print(f"[skip] {fig.name} (Fig {fig.number}) -- {fig.skip.split('.')[0]}.")
            continue
        if fig.owner:
            # Owned by a table generator; running it here would re-time a sweep.
            skipped.append(fig)
            print(f"[skip] {fig.name} (Fig {fig.number}) -- produced by {fig.owner}")
            continue

        print(f"[run ] {fig.name} (Fig {fig.number}) -- {fig.title}")
        proc = subprocess.run(command(fig), cwd=ROOT, env=environment(fig))
        if proc.returncode == 0:
            made.append(fig)
        else:
            failed.append(fig)
            print(f"[FAIL] {fig.name} exited {proc.returncode}", file=sys.stderr)

    # Only the proposal's own figures are installed. A study figure lives beside
    # the write-up it illustrates, under reproduce/outputs/figures/; copying it
    # into prose/fig/ would commit twelve files the document never cites.
    if made and not args.no_install:
        prose_names = {f.name for f in prose_figures()}
        installable = [f.name for f in made if f.name in prose_names]
        n = install(installable)
        held = len(made) - len(installable)
        print(
            f"\ninstalled {n} file(s) into "
            f"{os.path.relpath(PROSE_FIG, ROOT)}"
            + (
                f"; {held} study figure(s) left in " f"{os.path.relpath(FIG_OUT, ROOT)}"
                if held
                else ""
            )
        )

    print(f"\n{len(made)} drawn, {len(skipped)} skipped, {len(failed)} failed")
    for f in failed:
        print(f"  failed: {f.name}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
