"""Body fat % from body measurements, with `TribbleRegressor`.

The Penrose/Johnson body-fat dataset (252 men, 15 columns) with `BodyFat` as the
target.

**`Density` is not a feature -- it is the answer.** The dataset's `BodyFat`
column was not measured independently; it was *computed* from `Density` by
Siri's equation, %BF = 495/D - 450. Handing the model `Density` is therefore
handing it the target through a two-parameter closed form, and the resulting
near-perfect fit measures nothing. This script does not assert that -- it
reconstructs `BodyFat` from `Density` with Siri's equation and reports the
residual, then drops the column. Everything below predicts from the 13
anthropometric measurements (age, weight, height, and ten circumferences),
which is the problem worth solving: those are what a tape measure gives you,
where a hydrostatic-weighing tank is what `Density` needs.

Scored by 5-fold CV rather than one split -- 252 rows makes a single 20 % holdout
about 50 rows, too few for a stable RMSE -- repeated over five different fold
partitions, against three baselines: predicting the training mean, ordinary least
squares on the same 13 features, and OLS on `Abdomen` alone (one tape
measurement, the known dominant predictor). A fuzzy system that cannot beat one
circumference is not doing anything.

**The result is a draw at three features and a loss at thirteen.** OLS on all 13
measurements wins outright (RMSE 4.49). The fuzzy system's best configuration --
`tribblefis.scaling.MinMaxScaler` with an explicit log1p on the three
circumferences, config re-swept under that scaling -- reaches 4.82, level with
OLS on those same three features (4.71) and far better than the 7.02 it gets out
of the box. Body fat is close to linear in these circumferences, so the linear
model is hard to beat on its own ground.

**Scaling is the biggest lever here, and it is subtle.** The default estimator is
*invariant* to affine rescaling (raw, sklearn z-score, `tribblefis` min-max and
`tribblefis` z-score all give byte-identical RMSE), so only a nonlinear transform
moves it -- but affine scaling still matters indirectly, because `top_n` and
`l2_reg` are not scale-free and a config swept under one scaling does not
transfer to another. Automatic log detection never fires on this data (widest
feature spans 0.57 decades against a 3.0-decade threshold), so the log has to be
requested with `log_features`; the script prints the dynamic ranges so that is
checkable. The log helps the fuzzy model (5.05 -> 4.82) and hurts OLS
(4.71 -> 5.36).

The `Abdomen + Hip + Chest` subset is scored separately -- three circumferences
are a far better match for this estimator's capacity than thirteen features, and
it is the subset a clinician would actually measure. It is where every good fuzzy
result here comes from, and it also buys *stability*: the z-scored trio config
has a spread of 0.04 across fold partitions against 0.22 for the thirteen-feature
one. The interesting shape is that the fuzzy system scores about the same on
three features as on thirteen while OLS keeps improving as features are added --
the extra measurements carry linear information this configuration does not
convert into accuracy.

The Siri residual check also surfaces the dataset's known transcription errors as
a side effect, and physically impossible rows are reported and scored both ways
(kept and dropped), since a demo that silently repairs its data is not
reproducible.

Needs: numpy, pandas, scikit-learn, tribble-fis.  Run from the repo root:

    uv run --project tribble-fis python FuzzySystemsExperiments/bodyfat.py

Writes `FuzzySystemsExperiments/bodyfat_report.md`.
"""

import argparse
import contextlib
import io
import os
import time
import warnings

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

from tribblefis.gaussian_regressor import TribbleRegressor
from tribblefis.scaling import MinMaxScaler as FuzzyMinMaxScaler

REPORT = "FuzzySystemsExperiments/bodyfat_report.md"
DEFAULT_CSV = os.path.join("data", "bodyfat.csv")
TARGET = "BodyFat"
LEAKY = "Density"

# Siri's equation: the closed form the BodyFat column was generated by.
SIRI = (495.0, 450.0)

# Two configurations, and the gap between them is the point. Out of the box the
# estimator puts Gaussian antecedents on all 13 features and overfits 252 rows
# badly (RMSE ~7.5, fold spread +/-2.7). Capping the feature count and the
# Gaussians per feature, and leaning on the ridge, is what makes it competitive.
#
# `tuned` was chosen by a 288-point grid (top_n x n_gaussians x n_output_buckets
# x tsk_order x l2_reg) scored on seed 0's folds -- so it was selected with
# cross-validation visibility, and its seed-0 score is optimistic by
# construction. That is why every model here is re-scored over several
# *different* fold partitions: the selection seed is not the only one reported,
# and if the config were tuned to one partition's quirks the spread across seeds
# would show it.
CONFIGS = {
    "default": {},
    "tuned": {
        "top_n": 5,
        "n_gaussians": 2,
        "n_output_buckets": 4,
        "tsk_order": "1st",
        "l2_reg": 1.0,
    },
}

# The three-circumference subset, scored on its own because it is the natural
# question to ask of this dataset: abdomen, hip and chest are the measurements a
# clinician would actually take, and three features is a far better match for
# this estimator's capacity than thirteen. `TRIO_TUNED` is the best of a
# 144-point grid (n_gaussians x n_output_buckets x tsk_order x l2_reg) scored on
# *all* the partitions rather than one, so it carries no single-seed selection
# bias -- though picking the best of 144 on the same partitions it is reported on
# still flatters it a little, and the gap to OLS is larger than that flattery.
TRIO = ["Abdomen", "Hip", "Chest"]
TRIO_TUNED = {
    "n_gaussians": 1,
    "n_output_buckets": 4,
    "tsk_order": "1st",
    "l2_reg": 1e-2,
}

# The best fuzzy result on this dataset, and it comes from the *scaler*, not the
# estimator: `tribblefis.scaling.MinMaxScaler` bounding the three circumferences
# to [0, 1] after a log1p, with the config re-swept under that scaling.
#
# Three things about scaling on this dataset are worth stating, because each one
# is a trap:
#
#  1. **The default estimator is invariant to affine rescaling.** Raw features,
#     sklearn `StandardScaler`, `tribblefis` `MinMaxScaler` and `tribblefis`
#     `StandardScaler` all give byte-identical RMSE (7.021) for the default
#     config. Per-feature Gaussian membership fitting and least-squares
#     consequents are both unchanged by a per-feature affine map, so min-max vs
#     z-score cannot matter on its own. `tribblefis.scaling`'s warning that
#     z-scoring is actively harmful is documented for a pipeline with output
#     bucket means pinned to [0, 1] and a scaled target -- neither is in play
#     here, so it does not apply, and it is not contradicted either.
#
#  2. **Only a nonlinear transform moves the default model** -- which is what
#     makes the log the actual lever here (7.021 -> 6.358 on all 13).
#
#  3. **Automatic log detection never fires on this data.** It triggers at
#     `log_dynamic_range=3.0` decades, and the widest feature here spans 0.57
#     (`Age`); `Wrist` spans 0.13. So `MinMaxScaler()` and
#     `MinMaxScaler(log_dynamic_range=None)` are identical on bodyfat, and any
#     log has to be asked for explicitly with `log_features`. The script prints
#     the dynamic ranges so this is checkable rather than asserted.
#
# The log helps the fuzzy model (5.05 -> 4.82 on the trio) and *hurts* OLS
# (4.71 -> 5.36): the relationship really is closer to linear in raw units, and
# the log buys the fuzzy system a rule partition that fits better than it buys
# the linear model. Selected as the best of 64 configs scored on all the
# partitions, so it is mildly optimistic -- but the sixth-best log config
# (4.882) still beats the best no-log config (5.052), so the transform is doing
# the work rather than the search.
TRIO_LOG_TUNED = {
    "n_gaussians": 1,
    "n_output_buckets": 3,
    "tsk_order": "2nd",
    "l2_reg": 1e-2,
}


def fuzzy_log_scaler(cols):
    """`tribblefis`' own FIS scaler: log1p then bound to [0, 1], logging the
    named columns explicitly because automatic detection cannot fire here."""
    return lambda: FuzzyMinMaxScaler(log_features=list(cols))


def dynamic_ranges(df, cols):
    """Each feature's dynamic range in decades -- log10(max/min) over non-zero
    absolute values, the quantity `log_dynamic_range` thresholds."""
    rows = []
    for c in cols:
        v = np.abs(df[c].to_numpy(float))
        v = v[v > 0]
        rows.append({"feature": c, "decades": float(np.log10(v.max() / v.min()))})
    return pd.DataFrame(rows).sort_values("decades", ascending=False)


def rmse(y_true, y_pred):
    return float(np.sqrt(np.mean((np.asarray(y_true) - np.asarray(y_pred)) ** 2)))


def siri(density):
    """Body fat % from body density -- the equation this dataset's target came
    from."""
    a, b = SIRI
    return a / np.asarray(density, float) - b


def check_leakage(df):
    """Reconstruct the target from `Density` and report the residual, so the
    decision to drop that column rests on a number rather than on a claim.
    Returns (residual RMSE, frame of rows the equation does not reproduce)."""
    implied = siri(df[LEAKY])
    resid = df[TARGET].to_numpy(float) - implied
    bad = df.loc[np.abs(resid) > 1.0, [LEAKY, TARGET]].assign(
        siri_implied=implied[np.abs(resid) > 1.0], residual=resid[np.abs(resid) > 1.0]
    )
    return rmse(df[TARGET], implied), bad


def implausible(df):
    """Rows that cannot be physically right. Only one rule is needed here -- an
    adult height under 4 feet -- and it catches the dataset's known height typo.
    Reported, never silently repaired."""
    return df.index[df["Height"] < 48].tolist()


def cv_scores(model_factory, X, y, n_splits, seed, scale=True, scaler=None):
    """k-fold CV. The scaler is fit inside each fold, on the training part only.
    `scaler` is a zero-argument factory; it defaults to sklearn's
    `StandardScaler` when `scale` is true, and `scale=False` skips scaling
    entirely. Returns per-fold (rmse, mae, r2) and the out-of-fold predictions."""
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=seed)
    oof = np.zeros(len(y), float)
    folds = []
    make_scaler = scaler or (StandardScaler if scale else None)
    for tr, te in kf.split(X):
        X_tr, X_te = X.iloc[tr], X.iloc[te]
        if make_scaler is not None:
            fitted = make_scaler().fit(X_tr)
            X_tr = pd.DataFrame(fitted.transform(X_tr), columns=X.columns)
            X_te = pd.DataFrame(fitted.transform(X_te), columns=X.columns)
        pred = model_factory().fit(X_tr, y[tr]).predict(X_te)
        pred = np.asarray(pred, float).ravel()
        oof[te] = pred
        folds.append(
            (rmse(y[te], pred), mean_absolute_error(y[te], pred), r2_score(y[te], pred))
        )
    return np.array(folds), oof


def multi_seed_scores(model_factory, X, y, n_splits, seeds, scale=True, scaler=None):
    """The same CV repeated over several fold partitions. Returns the per-seed
    (rmse, mae, r2) means, the worst single fold's RMSE, and how many
    under-filled-bucket warnings the estimator raised -- the library's own signal
    that some rules were fitted on almost no data, which an aggregate RMSE
    hides."""
    per_seed, worst_fold, n_warnings = [], 0.0, 0
    for seed in seeds:
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            with contextlib.redirect_stdout(io.StringIO()):
                folds, _ = cv_scores(
                    model_factory, X, y, n_splits, seed, scale=scale, scaler=scaler
                )
        n_warnings += sum("under-filled" in str(w.message) for w in caught)
        worst_fold = max(worst_fold, folds[:, 0].max())
        per_seed.append(folds.mean(axis=0))
    return np.array(per_seed), worst_fold, n_warnings


class MeanRegressor:
    """The floor: predict the training mean for everyone."""

    def fit(self, X, y):
        self.mean_ = float(np.mean(y))
        return self

    def predict(self, X):
        return np.full(len(X), self.mean_)


def score_all(X, y, features, n_splits, seeds, quiet=False):
    """Every model in the comparison, scored identically over the same fold
    partitions."""
    rows = []

    def add(name, factory, cols=None, scale=True, scaler=None, note=""):
        per_seed, worst, n_warn = multi_seed_scores(
            factory,
            X[cols] if cols else X,
            y,
            n_splits,
            seeds,
            scale=scale,
            scaler=scaler,
        )
        rows.append(
            {
                "model": name,
                "scaling": note or ("z-score" if scale else "none"),
                "RMSE": per_seed[:, 0].mean(),
                "RMSE sd": per_seed[:, 0].std(),
                "MAE": per_seed[:, 1].mean(),
                "R2": per_seed[:, 2].mean(),
                "worst fold": worst,
                "starved-rule warnings": n_warn,
            }
        )
        if not quiet:
            print(
                f"  {name:38s} {rows[-1]['scaling']:14s} "
                f"RMSE {rows[-1]['RMSE']:5.2f} "
                f"± {rows[-1]['RMSE sd']:4.2f}  MAE {rows[-1]['MAE']:5.2f}  "
                f"R2 {rows[-1]['R2']:6.3f}  worst fold {worst:5.2f}"
                + (f"  [{n_warn} starved-rule warnings]" if n_warn else "")
            )
        return rows[-1]

    trio = "+".join(TRIO)
    add("mean predictor", MeanRegressor, scale=False)
    add("OLS, Abdomen only", LinearRegression, cols=["Abdomen"])
    add(f"OLS, {trio}", LinearRegression, cols=TRIO)
    add(f"OLS, all {len(features)} features", LinearRegression)
    for label, cfg in CONFIGS.items():
        add(
            f"TribbleRegressor ({label}), all {len(features)}",
            lambda c=cfg: TribbleRegressor(random_state=0, **c),
        )
    add(
        f"TribbleRegressor (default), {trio}",
        lambda: TribbleRegressor(random_state=0),
        cols=TRIO,
    )
    add(
        f"TribbleRegressor (tuned), {trio}",
        lambda: TribbleRegressor(random_state=0, **TRIO_TUNED),
        cols=TRIO,
    )
    add(
        f"TribbleRegressor (log-tuned), {trio}",
        lambda: TribbleRegressor(random_state=0, **TRIO_LOG_TUNED),
        cols=TRIO,
        scaler=fuzzy_log_scaler(TRIO),
        note="log1p + [0,1]",
    )
    return pd.DataFrame(rows)


def md_table(frame):
    cols = list(frame.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, row in frame.iterrows():
        lines.append(
            "| "
            + " | ".join(
                f"{row[c]:.3f}" if isinstance(row[c], float) else str(row[c])
                for c in cols
            )
            + " |"
        )
    return "\n".join(lines)


def write_report(path, ctx):
    best = ctx["scores"].loc[ctx["scores"]["model"].str.startswith("Tribble")]
    best = best.loc[best["RMSE"].idxmin()]
    ols = (
        ctx["scores"]
        .loc[ctx["scores"]["model"].str.startswith("OLS, all"), "RMSE"]
        .iloc[0]
    )
    lines = [
        "# Body fat % from body measurements (`TribbleRegressor`)",
        "",
        "Penrose/Johnson body-fat data: 252 men, `BodyFat` predicted from "
        "anthropometric measurements. Generated by "
        "`FuzzySystemsExperiments/bodyfat.py`.",
        "",
        "## `Density` is the answer, not a feature",
        "",
        f"The `BodyFat` column was computed from `Density` by Siri's equation, "
        f"%BF = {SIRI[0]:.0f}/D - {SIRI[1]:.0f}. Reconstructing it that way "
        f"reproduces the column to **RMSE {ctx['siri_rmse']:.3f} percentage "
        f"points** over all {ctx['n_rows']} rows -- so `Density` is not a "
        f"predictor of the target, it *is* the target in another coordinate. It "
        f"is excluded from every model below; the remaining "
        f"{len(ctx['features'])} features are what a tape measure and a scale "
        f"give you.",
        "",
    ]
    if len(ctx["siri_bad"]):
        lines += [
            f"The same check surfaces {len(ctx['siri_bad'])} rows the equation "
            f"does *not* reproduce -- the dataset's known transcription errors. "
            f"They are left in the data (reported, not repaired):",
            "",
            md_table(ctx["siri_bad"].reset_index().rename(columns={"index": "row"})),
            "",
        ]
    if ctx["implausible_rows"]:
        lines += [
            f"Separately, {len(ctx['implausible_rows'])} row(s) are physically "
            f"impossible -- "
            + ", ".join(
                f"row {i} has Height {ctx['df'].loc[i, 'Height']:.1f} in at "
                f"{ctx['df'].loc[i, 'Weight']:.1f} lb"
                for i in ctx["implausible_rows"]
            )
            + ", the dataset's documented height typo. Scored both ways below.",
            "",
        ]

    def rmse_of(prefix):
        hit = ctx["scores"].loc[ctx["scores"]["model"].str.startswith(prefix), "RMSE"]
        return hit.iloc[0]

    trio = "+".join(TRIO)
    abdomen = rmse_of("OLS, Abdomen only")
    mean_only = rmse_of("mean predictor")
    default = rmse_of("TribbleRegressor (default), all")
    ols_trio = rmse_of(f"OLS, {trio}")
    fuzzy_trio = min(
        rmse_of(f"TribbleRegressor (default), {trio}"),
        rmse_of(f"TribbleRegressor (tuned), {trio}"),
    )
    fuzzy_log = rmse_of(f"TribbleRegressor (log-tuned), {trio}")
    fuzzy_log_sd = (
        ctx["scores"]
        .loc[
            ctx["scores"]["model"].str.startswith(
                f"TribbleRegressor (log-tuned), {trio}"
            ),
            "RMSE sd",
        ]
        .iloc[0]
    )
    lines += [
        "## Cross-validated scores",
        "",
        f"{ctx['n_splits']}-fold CV repeated over {len(ctx['seeds'])} fold "
        f"partitions (seeds {', '.join(str(s) for s in ctx['seeds'])}); the "
        f"spread is across partitions, and one scaler is fit per fold on the "
        f"training part only. RMSE and MAE are in percentage points of body fat. "
        f"`worst fold` is the single worst fold anywhere in the run -- the number "
        f"a mean hides.",
        "",
        md_table(ctx["scores"]),
        "",
        "**Read the baselines first.**",
        "",
        f"- Predicting the training mean gives RMSE {mean_only:.2f}. That is the "
        f"floor.",
        f"- `Abdomen` alone -- one tape measurement -- gives **{abdomen:.2f}**. "
        f"This is the number that matters: any model that does not beat one "
        f"circumference is not earning its complexity.",
        f"- OLS on all {len(ctx['features'])} features gives **{ols:.2f}**, and "
        f"it is the best model here.",
        "",
        f"`TribbleRegressor` out of the box gives {default:.2f} -- worse than one "
        f"tape measurement, and barely better than the mean. Capping its capacity "
        f"and scaling its inputs properly (`{best['model']}`) brings it to "
        f"**{best['RMSE']:.2f} ± {best['RMSE sd']:.2f}**: past the "
        f"one-circumference baseline ({abdomen:.2f}), level with OLS on the same "
        f"three features ({ols_trio:.2f}), still behind OLS on all "
        f"{len(ctx['features'])} ({ols:.2f}).",
        "",
        "### Scaling, and the log transform",
        "",
        "Scaling is the single biggest lever found on this dataset, and it needs "
        "three facts stated before the numbers mean anything.",
        "",
        "**The default estimator is invariant to affine rescaling.** Raw "
        "features, sklearn `StandardScaler`, `tribblefis` `MinMaxScaler` and "
        "`tribblefis` `StandardScaler` all give a byte-identical RMSE of 7.021 "
        "for the default config. Per-feature Gaussian membership fitting and "
        "least-squares consequents are both unchanged by a per-feature affine "
        "map, so min-max versus z-score cannot matter on its own. "
        "(`tribblefis.scaling` warns that z-scoring is actively harmful to fuzzy "
        "models; that finding is documented for a pipeline with output bucket "
        "means pinned to `[0,1]` and a scaled target, neither of which is in "
        "play here — so it does not apply, and is not contradicted.)",
        "",
        "**Only a nonlinear transform moves the model**, which makes the log the "
        "real lever. Affine scaling does still matter *indirectly* for the tuned "
        "configs, because `top_n` feature selection and `l2_reg` are not "
        "scale-free: the same `l2_reg=1.0` that suits z-scored features is a "
        "crushing penalty on `[0,1]`-bounded ones (5.09 → 5.70). Configs "
        "therefore have to be re-swept under whatever scaling they will run in, "
        "which is what the `log-tuned` row is.",
        "",
        "**Automatic log detection never fires here.** It triggers at "
        "`log_dynamic_range=3.0` decades and the widest feature spans 0.57:",
        "",
        md_table(ctx["ranges"]),
        "",
        "So `MinMaxScaler()` and `MinMaxScaler(log_dynamic_range=None)` are "
        "identical on this data, and the log has to be named explicitly with "
        "`log_features`. With it named, the fuzzy model reaches its best result "
        "here — and the transform *hurts* OLS (4.71 → 5.36 on the trio) while "
        "helping the fuzzy system (5.05 → 4.82). The relationship really is "
        "closer to linear in raw units; the log buys a better rule partition "
        "without buying a better regression line.",
        "",
        f"### The `{trio}` subset",
        "",
        f"Three circumferences -- the measurements a clinician would actually "
        f"take, and a far better match for this estimator's capacity than "
        f"thirteen features. It does not rescue it. OLS on those three alone "
        f"gives **{ols_trio:.2f}**; the best fuzzy model on the same three gives "
        f"**{fuzzy_trio:.2f}**. Note where the two families end up: the fuzzy "
        f"system scores about the same on three features as on thirteen "
        f"({fuzzy_trio:.2f} vs {best['RMSE']:.2f}), while OLS keeps improving as "
        f"features are added ({ols_trio:.2f} -> {ols:.2f}). Extra measurements "
        f"carry linear information this TSK configuration does not convert into "
        f"accuracy.",
        "",
        f"That tuned figure is also a worked example of why the repeat over fold "
        f"partitions is here: on seed 0's folds alone -- the partition the "
        f"288-point grid search picked the config on -- it scored 4.85, and "
        f"across all {len(ctx['seeds'])} partitions it is {best['RMSE']:.2f}. The "
        f"0.2 pp difference is selection bias, not noise, and quoting the 4.85 "
        f"would have been quoting the search's own choice back at itself.",
        "",
        f"The `starved-rule warnings` column is the estimator's own complaint "
        f"that some output buckets were fitted on almost no data "
        f"({int(best['starved-rule warnings'])} such warnings for the tuned "
        "config): part of what looks like a working 4-rule model is rules with "
        "nearly nothing behind them.",
        "",
        f"**The honest conclusion.** With the right scaler the fuzzy model draws "
        f"level with OLS on the same three features -- {fuzzy_log:.2f} against "
        f"{ols_trio:.2f}, a gap inside its own ±{fuzzy_log_sd:.2f} "
        f"spread -- but still loses to OLS on all {len(ctx['features'])} "
        f"({ols:.2f}), and never beats it anywhere. Body fat is close to linear "
        f"in these circumferences, so the linear model is hard to beat on its "
        f"own ground; what the log transform buys the fuzzy system is a rule "
        f"partition good enough to match it, not to overtake it. The honest "
        f"reading is a draw at three features and a loss at thirteen -- which is "
        f"a better result than the first pass suggested, and it took the "
        f"library's own scaler to get there.",
        "",
    ]
    if ctx["scores_dropped"] is not None:
        lines += [
            "## With the implausible row(s) dropped",
            "",
            md_table(ctx["scores_dropped"]),
            "",
            "Same protocol, " f"{ctx['n_rows'] - len(ctx['implausible_rows'])} rows.",
            "",
        ]
    lines += [
        "## Features used",
        "",
        ", ".join(f"`{f}`" for f in ctx["features"]),
        "",
        f"Wall time: {ctx['wall_s']:.0f}s.",
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main(csv, n_splits, seeds, report):
    t0 = time.perf_counter()
    df = pd.read_csv(csv)
    print(f"{csv}: {len(df)} rows, {len(df.columns)} columns")

    siri_rmse, siri_bad = check_leakage(df)
    print(
        f"\nSiri's equation ({SIRI[0]:.0f}/Density - {SIRI[1]:.0f}) reproduces "
        f"{TARGET} to RMSE {siri_rmse:.3f} pp"
    )
    print(f"  -> dropping `{LEAKY}`: it is the target in another coordinate")
    if len(siri_bad):
        print(f"  {len(siri_bad)} row(s) the equation does not reproduce (kept as-is):")
        print(siri_bad.to_string(float_format="%.2f"))

    bad_rows = implausible(df)
    for i in bad_rows:
        print(
            f"\n  row {i}: Height {df.loc[i, 'Height']:.1f} in at "
            f"{df.loc[i, 'Weight']:.1f} lb -- physically impossible, the known "
            f"height typo. Kept; also scored without it below."
        )

    features = [c for c in df.columns if c not in (TARGET, LEAKY)]
    X, y = df[features], df[TARGET].to_numpy(float)

    ranges = dynamic_ranges(df, features)
    print(
        "\nFeature dynamic ranges (decades). `MinMaxScaler`'s automatic log "
        "detection fires at 3.0, so it selects nothing here -- any log has to be "
        "named explicitly via `log_features`:"
    )
    print("  " + ", ".join(f"{r.feature} {r.decades:.2f}" for r in ranges.itertuples()))

    print(
        f"\n{n_splits}-fold CV over {len(seeds)} fold partitions (seeds "
        f"{', '.join(str(s) for s in seeds)}) on {len(features)} measurements, "
        f"{len(df)} rows:"
    )
    scores = score_all(X, y, features, n_splits, seeds)

    scores_dropped = None
    if bad_rows:
        kept = df.drop(index=bad_rows).reset_index(drop=True)
        print(f"\nSame, with row(s) {bad_rows} dropped ({len(kept)} rows):")
        scores_dropped = score_all(
            kept[features], kept[TARGET].to_numpy(float), features, n_splits, seeds
        )

    ctx = {
        "df": df,
        "n_rows": len(df),
        "features": features,
        "ranges": ranges,
        "siri_rmse": siri_rmse,
        "siri_bad": siri_bad,
        "implausible_rows": bad_rows,
        "n_splits": n_splits,
        "seeds": seeds,
        "scores": scores,
        "scores_dropped": scores_dropped,
        "wall_s": time.perf_counter() - t0,
    }
    write_report(report, ctx)
    print(f"\nwrote {report}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--csv", default=DEFAULT_CSV)
    p.add_argument("--folds", type=int, default=5)
    p.add_argument(
        "--seeds",
        default="0,1,2,3,4",
        help="Comma-separated CV partition seeds; every model is scored on all "
        "of them and reported as mean ± std (default 0,1,2,3,4).",
    )
    p.add_argument("--report", default=REPORT)
    a = p.parse_args()
    main(a.csv, a.folds, [int(s) for s in a.seeds.split(",") if s.strip()], a.report)
