"""Shared helpers for the experiment-table generators.

Keep the table scripts thin: they load data, fit models over a fixed set of
seeds, and hand (mean, std) cells to the emitters here. Everything about *how a
table renders* lives in this file, so all tables look the same.
"""

from __future__ import annotations

import csv
import os
import statistics
import time
from contextlib import contextmanager

# Fixed seeds -> every reported number is mean +/- std across these.
#
# Ten, not five. The proposal's tables were originally transcribed from 3-seed
# runs, and several Chapter 4 conclusions that looked decisive there turned out
# to sit inside the seed-to-seed spread once the harness widened it. Ten is the
# standard the chapters are now quoted at; narrowing it changes what the document
# can claim, so treat it as part of the protocol rather than a tuning knob.
# Override with REPRO_SEEDS="0,1,2" for a quick smoke run.
SEEDS = [int(s) for s in
         os.environ.get("REPRO_SEEDS", "0,1,2,3,4,5,6,7,8,9").split(",")]

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                          "reproduce", "outputs")

NA = "N/A"          # column that genuinely could not be produced (missing dep/data)


@contextmanager
def timed():
    """`with timed() as t: ...; t.seconds` -> wall-clock seconds of the block."""
    class _T:
        seconds = 0.0
    t = _T()
    start = time.perf_counter()
    try:
        yield t
    finally:
        t.seconds = time.perf_counter() - start


def agg(values):
    """(mean, std) of a list; std=0 for a single value. Returns (None, None) if empty."""
    vals = [v for v in values if v is not None]
    if not vals:
        return None, None
    mean = statistics.fmean(vals)
    std = statistics.pstdev(vals) if len(vals) > 1 else 0.0
    return mean, std


def cell(values, fmt="{:.3f}", na=NA):
    """Render a list of per-seed values as 'mean ± std', or the NA marker."""
    mean, std = agg(values)
    if mean is None:
        return na
    if std and std > 0:
        return f"{fmt.format(mean)} ± {fmt.format(std)}"
    return fmt.format(mean)


def write_markdown(path, title, header, rows, note=""):
    """Write a GitHub-flavored Markdown table."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(f"**{title}**\n\n")
        f.write("| " + " | ".join(header) + " |\n")
        f.write("|" + "|".join(["---"] * len(header)) + "|\n")
        for r in rows:
            f.write("| " + " | ".join(str(c) for c in r) + " |\n")
        if note:
            f.write(f"\n> {note}\n")
        f.write(f"\n> Generated by `reproduce/`; seeds = {SEEDS}. "
                f"`{NA}` marks a cell whose method/dataset was unavailable.\n")
    print(f"  wrote {path}")


def write_csv(path, header, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    print(f"  wrote {path}")


def emit(basename, title, header, rows, note=""):
    """Write both .md and .csv for one table into reproduce/outputs/."""
    md = os.path.join(OUTPUT_DIR, f"{basename}.md")
    cv = os.path.join(OUTPUT_DIR, f"{basename}.csv")
    write_markdown(md, title, header, rows, note)
    write_csv(cv, header, rows)


def optional_import(modpath, names):
    """Return the requested attributes, or None for each if the import fails.

    Lets a table skip a baseline (ANFIS, M5, ...) cleanly instead of crashing.
    """
    try:
        mod = __import__(modpath, fromlist=list(names))
        return [getattr(mod, n, None) for n in names]
    except Exception as exc:  # noqa: BLE001 - deliberately broad; report and skip
        print(f"  [skip] {modpath} unavailable ({exc.__class__.__name__}); "
              f"columns {names} -> {NA}")
        return [None] * len(names)
