name = "FuzzySymphonyProofs"
defaultTargets = ["FuzzySymphonyProofs"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0-patch1"

[[lean_lib]]
name = "FuzzySymphonyProofs"
